/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgVue;

import java.util.List;
import javax.swing.JComboBox;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.event.RefreshEvent;
import pkgEntite.HibernateUtil;
import pkgEntite.Joueur;

/**
 *
 * @author Maxence
 */
public class jframe extends javax.swing.JFrame {

    /**
     * Creates new form jframe
     */
    public jframe() {
        initComponents();
    }
boolean charge = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnrejouer = new javax.swing.JButton();
        jbtnajouter = new javax.swing.JButton();
        jbtnOk = new javax.swing.JButton();
        jbtnenregistrer = new javax.swing.JButton();
        jcbutilisateur = new javax.swing.JComboBox();
        jtxtnom = new javax.swing.JTextField();
        jtxtcode1 = new javax.swing.JTextField();
        jTxtaffichage = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jbtnrejouer.setText("Rejouer");
        jbtnrejouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrejouerActionPerformed(evt);
            }
        });

        jbtnajouter.setText("Ajouter");
        jbtnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnajouterActionPerformed(evt);
            }
        });

        jbtnOk.setText("Valider");
        jbtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOkActionPerformed(evt);
            }
        });

        jbtnenregistrer.setText("Enregistrer");
        jbtnenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnenregistrerActionPerformed(evt);
            }
        });

        jcbutilisateur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbutilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbutilisateurActionPerformed(evt);
            }
        });

        jtxtnom.setText("Nom");

        jtxtcode1.setText("Code");

        jTxtaffichage.setText("jTextField1");

        jMenu1.setText("File");

        jMenuItem1.setText("Quitter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnrejouer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnenregistrer)
                        .addGap(57, 174, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbtnajouter))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnOk)
                            .addComponent(jcbutilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtaffichage, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jcbutilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jTxtaffichage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtcode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 48, Short.MAX_VALUE)
                .addComponent(jtxtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOk)
                    .addComponent(jbtnajouter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnrejouer)
                    .addComponent(jbtnenregistrer))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnrejouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrejouerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnrejouerActionPerformed

    private void jbtnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnajouterActionPerformed
       Session session = HibernateUtil.getSessionFactory().openSession();
        Joueur unNouveauJoueur = new Joueur(jtxtcode1.getText());
        unNouveauJoueur.setJouNom(jtxtnom.getText());
        Transaction tx = session.beginTransaction();
        session.save(unNouveauJoueur);
        tx.commit();   // TODO add your handling code here:
    }//GEN-LAST:event_jbtnajouterActionPerformed

    private void jbtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOkActionPerformed
  Session session = HibernateUtil.getSessionFactory().openSession();
        Joueur unNouveauJoueur = new Joueur(jtxtcode1.getText());
        unNouveauJoueur.setJouNom(jtxtnom.getText());
        System.out.println(unNouveauJoueur.getJouCode() +" - "+ unNouveauJoueur.getJouNom());
        Transaction tx = session.beginTransaction();
        session.save(unNouveauJoueur);
        tx.commit();   
        jcbutilisateur.removeAllItems();
        test();
        //pack();// TODO add your handling code here:
    }//GEN-LAST:event_jbtnOkActionPerformed

    private void jbtnenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnenregistrerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnenregistrerActionPerformed

    private void jcbutilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbutilisateurActionPerformed

if (charge == true){
//String unJoueur = ((String)jcbutilisateur.getSelectedItem());
//Joueur unJoueur = (Joueur) (jcbutilisateur.getSelectedItem());
JComboBox test = new JComboBox();
test.getSelectedItem().toString();
/*String code = unJoueur.getJouCode();
String nom = unJoueur.getJouNom();

jTxtaffichage.setText(unJoueur.getJouCode());*/}
        //System.out.println(sResultat);
        /*Iterator joueur = qm.iterate();
        sResultat="";
        while (joueur.hasNext()){
            Joueur leJoueur = (Joueur) joueur.next();
            sResultat+=leJoueur.getJouNom()+"\n";
        } System.out.println(sResultat); */  // TODO add your handling code here:
    }//GEN-LAST:event_jcbutilisateurActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       // jbtnajouter.hide();
        jbtnrejouer.hide();
        jbtnenregistrer.hide();
        test();
        
               // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
 System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    private void test(){
        Session session = HibernateUtil.getSessionFactory().openSession();
        Joueur unNouveauJoueur = new Joueur("ZZ");
        unNouveauJoueur.setJouNom("Test");
       // Transaction tx = session.beginTransaction();
        String sReqm = "from Joueur";
        Query qm = session.createQuery(sReqm); 
        List<Joueur> lesJoueurs = qm.list();
        String sResultat ="";
        jcbutilisateur.removeAllItems();
        for(int i=0; i <lesJoueurs.size(); i++)
        {
            sResultat+=lesJoueurs.get(i).getJouNom()+ "\n";
            jcbutilisateur.addItem(lesJoueurs.get(i).getJouNom());
        charge = true;} 
        jTxtaffichage.requestFocus();
       // charge = true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jTxtaffichage;
    private javax.swing.JButton jbtnOk;
    private javax.swing.JButton jbtnajouter;
    private javax.swing.JButton jbtnenregistrer;
    private javax.swing.JButton jbtnrejouer;
    private javax.swing.JComboBox jcbutilisateur;
    private javax.swing.JTextField jtxtcode1;
    private javax.swing.JTextField jtxtnom;
    // End of variables declaration//GEN-END:variables
}
