/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgVue;

import java.util.Iterator;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import pkgEntite.HibernateUtil;
import pkgEntite.Joueur;

/**
 *
 * @author Maxence
 */
public class JPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPanel
     */
    public JPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblproposition = new javax.swing.JLabel();
        jbtnOk = new javax.swing.JButton();
        jbtnefface = new javax.swing.JButton();
        jbtnrejouer = new javax.swing.JButton();
        jbtnenregistrer = new javax.swing.JButton();
        jcbutilisateur = new javax.swing.JComboBox();

        jlblproposition.setText("Proposition");

        jbtnOk.setText("Valider");
        jbtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOkActionPerformed(evt);
            }
        });

        jbtnefface.setText("Efface");
        jbtnefface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneffaceActionPerformed(evt);
            }
        });

        jbtnrejouer.setText("Rejouer");
        jbtnrejouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrejouerActionPerformed(evt);
            }
        });

        jbtnenregistrer.setText("Enregistrer");
        jbtnenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnenregistrerActionPerformed(evt);
            }
        });

        jcbutilisateur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbutilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbutilisateurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnrejouer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnenregistrer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnefface)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbutilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnOk))))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlblproposition)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblproposition)
                .addGap(64, 64, 64)
                .addComponent(jcbutilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOk)
                    .addComponent(jbtnefface))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnrejouer)
                    .addComponent(jbtnenregistrer))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnOkActionPerformed

    private void jbtneffaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneffaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtneffaceActionPerformed

    private void jbtnrejouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrejouerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnrejouerActionPerformed

    private void jbtnenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnenregistrerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnenregistrerActionPerformed

    private void jcbutilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbutilisateurActionPerformed
        Session session = HibernateUtil.getSessionFactory().openSession();
        Joueur unNouveauJoueur = new Joueur("ZZ");
        unNouveauJoueur.setJouNom("Test");
        Transaction tx = session.beginTransaction();
        String sReqm = "from Joueur";
    Query qm = session.createQuery(sReqm); List<Joueur> lesJoueurs = qm.list();
    String sResultat ="";
    for(int i=0; i <lesJoueurs.size(); i++)
    {
    sResultat+=lesJoueurs.get(i).getJouNom()+ "\n"; 
    jcbutilisateur.addItem(lesJoueurs.get(i).getJouNom());}
    //System.out.println(sResultat);
    /*Iterator joueur = qm.iterate();
    sResultat="";
    while (joueur.hasNext()){
    Joueur leJoueur = (Joueur) joueur.next();
    sResultat+=leJoueur.getJouNom()+"\n";
    } System.out.println(sResultat); */  // TODO add your handling code here:
    }//GEN-LAST:event_jcbutilisateurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnOk;
    private javax.swing.JButton jbtnefface;
    private javax.swing.JButton jbtnenregistrer;
    private javax.swing.JButton jbtnrejouer;
    private javax.swing.JComboBox jcbutilisateur;
    private javax.swing.JLabel jlblproposition;
    // End of variables declaration//GEN-END:variables
}
