package pkgEntite;
// Generated 19 mars 2014 20:54:55 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Joueur generated by hbm2java
 */
public class Joueur  implements java.io.Serializable {


     private String jouCode;
     private String jouNom;
     private Set parties = new HashSet(0);

    public Joueur() {
    }
    public Joueur(String jouCode){
        this.jouCode = jouCode;
    }
	
    public Joueur(String jouCode, String jouNom) {
        this.jouCode = jouCode;
        this.jouNom = jouNom;
    }
    public Joueur(String jouCode, String jouNom, Set parties) {
       this.jouCode = jouCode;
       this.jouNom = jouNom;
       this.parties = parties;
    }
   
    public String getJouCode() {
        return this.jouCode;
    }
    
    public void setJouCode(String jouCode) {
        this.jouCode = jouCode;
    }
    public String getJouNom() {
        return this.jouNom;
    }
    
    public void setJouNom(String jouNom) {
        this.jouNom = jouNom;
    }
    public Set getParties() {
        return this.parties;
    }
    
    public void setParties(Set parties) {
        this.parties = parties;
    }




}


